### PR TITLE
changed to new style colors on back-to-top

### PR DESCRIPTION
**Pull request by mthege**
Change color of icon and background color according to new style colors.

[AB#4272](https://dev.azure.com/kth-integration/f3bf8cac-2bdc-4cc2-92e4-2ab44dcc461c/_workitems/edit/4272)

### CODE REVIEW

**Review by falric — APPROVED** [review]
I think it looks good and less jarring against the footer. Maybe @EllenWiderstrand or @exacs should weigh in as well?

**Review by ahrsjo — APPROVED** [review]
giphy

**Comment by ahrsjo** [comment]
Again with the github to boards connection not working 😢

**Comment by ahrsjo** [comment]
> Again with the github to boards connection not working 😢

Now it's working 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
